@startuml
start
: Scanner myReader;
: Int number;
:Ausgabe: Geben Sie eine Ganzzahl ein!;
:ArrayListe<Integer> Teilerliste;
:myReader -> number ;
: for (int i = 2;i <= number/2; i++);
if (number % i == 0) is (yes) then
  :true;
  :Teiler.add(i);
else (no)
  :false;
endif
:Ausgabe: teilerListe;

@enduml