@startuml
class Klassname {
Attribute
Metoden()
}
class Buch {
Titel : String
ISBN : int
}

Klassname - Buch

class Bestellung {}
Bestellung --|> Buch
class Buchhandlung {}
class Regal {}
Buchhandlung *- Regal

Buchhandlung o-- Buch

@enduml