@startuml
 state Offen {
  [*] --> Arbeiten
  Arbeiten --> Pause
 }
 state Geschlossen
  Geschlossen-> Offen
  ' orthogonalen Zustand

  state Buchhandlung {
  [*] -> Suchnend
  Suchnend -> [*]
  note right of Suchnend
  Geist
  end note
  --
  [*] -> Gehend
  Gehend -> [*]
  note right of Gehend
  Körper
  end note
  }

@enduml