@startuml
left to right direction
actor  Customer
rectangle Banking-App {
  Customer -- (Log In)
  Customer -- (Check Balance)
  Customer -- (Transfer Funds)
  Customer -- (Make Payment)

  (Log In)
  (Check Balance)
  (Transfer Funds)
  (Make Payment)
  (Set Up Profile)

  (Log In) ..> (Verify Password) : <<include>>
  (Log In) <.. (Display Login Error) : <<include>>
  (Transfer Funds) ..> (Verify Sufficient  Funds) : <<include>>
  (Make Payment) ..> (Verify Sufficient  Funds) : <<include>>

  (Pay from Checking) -|> (Make Payment)
  (Pay from Savings) -|> (Make Payment)

  Customer -- (Set Up Profile)

  (Go to Profile Help) <.. (Set Up Profile) : <<extend>>
  (Show Privacy Info) <.. (Set Up Profile) : <<extend>>
}

actor Bank
(Check Balance) -- Bank
(Transfer Funds) -- Bank
(Make Payment) -- Bank


@enduml