@startuml
class Mitarbeiter {
  -name : String
--
  +Mitarbeiter()
  +getMitarbeiter()
  +setMitarbeiter()
}
class Raum {
  -raumNr : Integer
--
  +Raum()
  +setRaum()
  +getRaum()
}
Mitarbeiter -- "0...1" Raum
@enduml