@startuml
class Mitarbeiter {
  -name : String
--
  +Mitarbeiter()
  +getMitarbeiter()
  +setMitarbeiter()
}
class Auto {
  -kfzKennzeichen : String
 --
  +Auto()
  +getKfzKennzeichen() : String
  +setKfzKennzeichen(KfzKennnzeicen:String) :void
}
Mitarbeiter --> "0..1" Auto
@enduml