@startuml
class Wuerfel {
- standartFarbe: Color
-standardFarbe:Color
-xPos: int
-yPos: int
-breite: int
-hoehe: int
-farbe: Color
-wert: int
-gueltig: boolean
--
+<construct>> Wuefel()
+«construct» Wuerfel(xPos:int, yPos:int,breite:int, hoehe:int)
+«construct» Wuerfel(xPos:int, yPos:int,breite:int, hoehe:int, farbe: String)
+setFarbeWuefel(farbe: Color): void
+wuerfeln(: void
+
}
@enduml